# Form implementation generated from reading ui file 'streetfighter.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Player:
    def __init__(self, player_name, player_power, player_speed, player_agility):
        self.name = player_name
        self.power = player_power
        self.speed = player_speed
        self.agility = player_agility
        
    def modify_stats(self, player_power, player_speed, player_agility):
        self.power = player_power
        self.speed = player_speed
        self.agility = player_agility

class Ui_streetFighter(object):
    def setupUi(self, streetFighter):
        streetFighter.setObjectName("streetFighter")
        streetFighter.resize(536, 434)
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        streetFighter.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=streetFighter)
        self.centralwidget.setObjectName("centralwidget")
        self.tbStreetFighter = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tbStreetFighter.setGeometry(QtCore.QRect(10, 10, 511, 361))
        self.tbStreetFighter.setObjectName("tbStreetFighter")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtName = QtWidgets.QLineEdit(parent=self.tab)
        self.txtName.setGeometry(QtCore.QRect(240, 50, 113, 20))
        self.txtName.setObjectName("txtName")
        self.lblName = QtWidgets.QLabel(parent=self.tab)
        self.lblName.setGeometry(QtCore.QRect(120, 50, 101, 21))
        self.lblName.setObjectName("lblName")
        self.lblPower = QtWidgets.QLabel(parent=self.tab)
        self.lblPower.setGeometry(QtCore.QRect(120, 100, 101, 21))
        self.lblPower.setObjectName("lblPower")
        self.txtPower = QtWidgets.QLineEdit(parent=self.tab)
        self.txtPower.setGeometry(QtCore.QRect(240, 100, 113, 20))
        self.txtPower.setText("")
        self.txtPower.setObjectName("txtPower")
        self.txtSpeed = QtWidgets.QLineEdit(parent=self.tab)
        self.txtSpeed.setGeometry(QtCore.QRect(240, 150, 113, 20))
        self.txtSpeed.setText("")
        self.txtSpeed.setObjectName("txtSpeed")
        self.lblSpeed = QtWidgets.QLabel(parent=self.tab)
        self.lblSpeed.setGeometry(QtCore.QRect(120, 150, 101, 21))
        self.lblSpeed.setObjectName("lblSpeed")
        self.lblAgility = QtWidgets.QLabel(parent=self.tab)
        self.lblAgility.setGeometry(QtCore.QRect(120, 200, 101, 21))
        self.lblAgility.setObjectName("lblAgility")
        self.txtAgility = QtWidgets.QLineEdit(parent=self.tab)
        self.txtAgility.setGeometry(QtCore.QRect(240, 200, 113, 20))
        self.txtAgility.setText("")
        self.txtAgility.setObjectName("txtAgility")
        self.btnCreate = QtWidgets.QPushButton(parent=self.tab)
        self.btnCreate.setGeometry(QtCore.QRect(200, 260, 101, 31))
        self.btnCreate.setObjectName("btnCreate")
        self.tbStreetFighter.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lstPlayers = QtWidgets.QListWidget(parent=self.tab_2)
        self.lstPlayers.setGeometry(QtCore.QRect(90, 60, 321, 91))
        self.lstPlayers.setObjectName("lstPlayers")
        self.lblCreated = QtWidgets.QLabel(parent=self.tab_2)
        self.lblCreated.setGeometry(QtCore.QRect(170, 20, 161, 21))
        self.lblCreated.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblCreated.setObjectName("lblCreated")
        self.txtModPower = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModPower.setGeometry(QtCore.QRect(160, 180, 113, 20))
        self.txtModPower.setObjectName("txtModPower")
        self.lblModPower = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModPower.setGeometry(QtCore.QRect(40, 180, 101, 21))
        self.lblModPower.setObjectName("lblModPower")
        self.txtModSpeed = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModSpeed.setGeometry(QtCore.QRect(160, 230, 113, 20))
        self.txtModSpeed.setObjectName("txtModSpeed")
        self.lblModSpeed = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModSpeed.setGeometry(QtCore.QRect(40, 230, 101, 21))
        self.lblModSpeed.setObjectName("lblModSpeed")
        self.txtModAgility = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtModAgility.setGeometry(QtCore.QRect(160, 280, 113, 20))
        self.txtModAgility.setObjectName("txtModAgility")
        self.lblModAgility = QtWidgets.QLabel(parent=self.tab_2)
        self.lblModAgility.setGeometry(QtCore.QRect(40, 280, 101, 21))
        self.lblModAgility.setObjectName("lblModAgility")
        self.btnModPlayer = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnModPlayer.setGeometry(QtCore.QRect(340, 220, 111, 31))
        self.btnModPlayer.setObjectName("btnModPlayer")
        self.tbStreetFighter.addTab(self.tab_2, "")
        streetFighter.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=streetFighter)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 536, 23))
        self.menubar.setObjectName("menubar")
        streetFighter.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=streetFighter)
        self.statusbar.setObjectName("statusbar")
        streetFighter.setStatusBar(self.statusbar)

        self.retranslateUi(streetFighter)
        self.tbStreetFighter.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(streetFighter)
        
        # Create an empty dictionary to store players
        self.created_players = {}
        
        self.btnCreate.clicked.connect(self.create_player)
        
        self.lstPlayers.itemClicked.connect(self.display_stats)
        
        self.btnModPlayer.clicked.connect(self.modify_player)
        
        # To do:
        # 1) Input Validation
        # 2) Exception Handling
        # 3) Message boxes
        # 4) Add comments

    def modify_player(self):
        player_name = self.lstPlayers.currentItem().text()
        player_object = self.created_players.get(player_name)
        modified_power = self.txtModPower.text()
        modified_speed = self.txtModSpeed.text()
        modified_agility = self.txtModAgility.text()
        
        player_object.modify_stats(modified_power, modified_speed, modified_agility)
    
    def display_stats(self):
        player_name = self.lstPlayers.currentItem().text()
        player_object = self.created_players.get(player_name)
        self.txtModPower.setText(player_object.power)
        self.txtModSpeed.setText(player_object.speed)
        self.txtModAgility.setText(player_object.agility)
    
    def create_player(self):
        player_name = self.txtName.text()
        player_power = self.txtPower.text()
        player_speed = self.txtSpeed.text()
        player_agility = self.txtAgility.text()
        # Player object creation
        player_object = Player(player_name, player_power, player_speed, player_agility)
        # Storing the player object in the dictionary
        self.created_players[player_name] = player_object
        
        self.lstPlayers.addItem(player_name)
    
    def retranslateUi(self, streetFighter):
        _translate = QtCore.QCoreApplication.translate
        streetFighter.setWindowTitle(_translate("streetFighter", "Street Fighter"))
        self.lblName.setText(_translate("streetFighter", "Enter Player Name:"))
        self.lblPower.setText(_translate("streetFighter", "Enter Player Power:"))
        self.lblSpeed.setText(_translate("streetFighter", "Enter Player Speed:"))
        self.lblAgility.setText(_translate("streetFighter", "Enter Player Agility:"))
        self.btnCreate.setText(_translate("streetFighter", "Create Player"))
        self.tbStreetFighter.setTabText(self.tbStreetFighter.indexOf(self.tab), _translate("streetFighter", "Create Player"))
        self.lblCreated.setText(_translate("streetFighter", "List of Previous Players:"))
        self.lblModPower.setText(_translate("streetFighter", "Modify Power:"))
        self.lblModSpeed.setText(_translate("streetFighter", "Modify Speed:"))
        self.lblModAgility.setText(_translate("streetFighter", "Modify Agility:"))
        self.btnModPlayer.setText(_translate("streetFighter", "Modify Player"))
        self.tbStreetFighter.setTabText(self.tbStreetFighter.indexOf(self.tab_2), _translate("streetFighter", "Modify Player"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    streetFighter = QtWidgets.QMainWindow()
    ui = Ui_streetFighter()
    ui.setupUi(streetFighter)
    streetFighter.show()
    sys.exit(app.exec())
