# Form implementation generated from reading ui file 'dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from purchase import Ui_purchase
from search import Ui_search
from display import Ui_display

class Ui_dashboard(object):
    def setupUi(self, dashboard):
        dashboard.setObjectName("dashboard")
        dashboard.resize(707, 425)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        dashboard.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=dashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.lblName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblName.setGeometry(QtCore.QRect(180, 120, 111, 21))
        self.lblName.setObjectName("lblName")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(340, 120, 181, 20))
        self.txtName.setObjectName("txtName")
        self.btnPurchase = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPurchase.setGeometry(QtCore.QRect(150, 180, 111, 31))
        self.btnPurchase.setObjectName("btnPurchase")
        self.btnSearch = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSearch.setGeometry(QtCore.QRect(290, 180, 111, 31))
        self.btnSearch.setObjectName("btnSearch")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(430, 180, 111, 31))
        self.btnDisplay.setObjectName("btnDisplay")
        self.btnExit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(280, 300, 111, 31))
        self.btnExit.setObjectName("btnExit")
        dashboard.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=dashboard)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 707, 17))
        self.menubar.setObjectName("menubar")
        dashboard.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=dashboard)
        self.statusbar.setObjectName("statusbar")
        dashboard.setStatusBar(self.statusbar)

        self.retranslateUi(dashboard)
        QtCore.QMetaObject.connectSlotsByName(dashboard)
        
        # When this button is clicked, the purchase window will show
        self.btnPurchase.clicked.connect(self.purchase_window)
        
        # When this button is clicked, the search window will show
        self.btnSearch.clicked.connect(self.search_window)
        
        # When this button is clicked, the display window will show
        self.btnDisplay.clicked.connect(self.display_window)
        
        # When this button is clicked, the application will exit
        self.btnExit.clicked.connect(self.exit_app)
        
    def display_window(self):
         # Create an empty Main Window
        self.window = QtWidgets.QMainWindow()
        
        # Create a new object from the display app
        self.displayui = Ui_display()
        
        # Call the setupUifunction of the display app
        self.displayui.setupUi(self.window)
        
        # Display the Window
        self.window.show()
    
    def purchase_window (self):
        # Create an empty Main Window
        self.window = QtWidgets.QMainWindow()
        
        # Create a new object from the purchase app
        self.purchaseui = Ui_purchase()
        
        # Call the setupUifunction of the purchase application
        self.purchaseui.setupUi(self.window)
        
        customer_name = self.txtName.text()
        self.purchaseui.set_cname(customer_name)
        
        # Display the Window
        self.window.show()
    
    def search_window (self):
        # Create an empty Main Window
        self.window = QtWidgets.QMainWindow()
        
        # Create a new object from the search application
        self.searchui = Ui_search()
        
        # Call the setupUifunction of the search application
        self.searchui.setupUi(self.window)
        
        # Display the Window
        self.window.show()
        
    def exit_app(self):
        # When the exit button is clicked, this will quit the application
        QtWidgets.QApplication.quit()


    def retranslateUi(self, dashboard):
        _translate = QtCore.QCoreApplication.translate
        dashboard.setWindowTitle(_translate("dashboard", "Dashboard"))
        self.lblName.setText(_translate("dashboard", "Enter Name:"))
        self.btnPurchase.setText(_translate("dashboard", "Purchase"))
        self.btnSearch.setText(_translate("dashboard", "Search"))
        self.btnDisplay.setText(_translate("dashboard", "Display"))
        self.btnExit.setText(_translate("dashboard", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dashboard = QtWidgets.QMainWindow()
    ui = Ui_dashboard()
    ui.setupUi(dashboard)
    dashboard.show()
    sys.exit(app.exec())
