# Form implementation generated from reading ui file 'fruit.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_fruitPurchase(object):
    def setupUi(self, fruitPurchase):
        fruitPurchase.setObjectName("fruitPurchase")
        fruitPurchase.resize(436, 411)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        fruitPurchase.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=fruitPurchase)
        self.centralwidget.setObjectName("centralwidget")
        self.lblFruit = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblFruit.setGeometry(QtCore.QRect(100, 70, 91, 21))
        self.lblFruit.setObjectName("lblFruit")
        self.cmbFruit = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbFruit.setGeometry(QtCore.QRect(180, 60, 131, 31))
        self.cmbFruit.setObjectName("cmbFruit")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.cmbFruit.addItem("")
        self.lblQuantity = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblQuantity.setGeometry(QtCore.QRect(100, 130, 91, 21))
        self.lblQuantity.setObjectName("lblQuantity")
        self.txtQuantity = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtQuantity.setGeometry(QtCore.QRect(180, 120, 131, 31))
        self.txtQuantity.setObjectName("txtQuantity")
        self.btnCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCalculate.setGeometry(QtCore.QRect(190, 180, 111, 31))
        self.btnCalculate.setObjectName("btnCalculate")
        self.lblCost = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblCost.setGeometry(QtCore.QRect(100, 250, 91, 21))
        self.lblCost.setObjectName("lblCost")
        self.txtCost = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCost.setGeometry(QtCore.QRect(180, 240, 131, 31))
        self.txtCost.setReadOnly(True)
        self.txtCost.setObjectName("txtCost")
        self.lblPrice = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblPrice.setGeometry(QtCore.QRect(330, 60, 91, 21))
        self.lblPrice.setText("")
        self.lblPrice.setObjectName("lblPrice")
        fruitPurchase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=fruitPurchase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 436, 17))
        self.menubar.setObjectName("menubar")
        fruitPurchase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=fruitPurchase)
        self.statusbar.setObjectName("statusbar")
        fruitPurchase.setStatusBar(self.statusbar)

        self.retranslateUi(fruitPurchase)
        QtCore.QMetaObject.connectSlotsByName(fruitPurchase)
        
        self.fruit_price = {"Apple": 3.50, "Orange": 3.99, "Pear": 4.10, "Peach":5.99, "Banana": 1.29}
        
        self.cmbFruit.currentIndexChanged.connect(self.display_price)
        
        self.btnCalculate.clicked.connect(self.calculate)

    def retranslateUi(self, fruitPurchase):
        _translate = QtCore.QCoreApplication.translate
        fruitPurchase.setWindowTitle(_translate("fruitPurchase", "Fruit Purchase"))
        self.lblFruit.setText(_translate("fruitPurchase", "Select a fruit:"))
        self.cmbFruit.setItemText(0, _translate("fruitPurchase", "Fruit Selection"))
        self.cmbFruit.setItemText(1, _translate("fruitPurchase", "Apple"))
        self.cmbFruit.setItemText(2, _translate("fruitPurchase", "Orange"))
        self.cmbFruit.setItemText(3, _translate("fruitPurchase", "Pear"))
        self.cmbFruit.setItemText(4, _translate("fruitPurchase", "Peach"))
        self.cmbFruit.setItemText(5, _translate("fruitPurchase", "Banana"))
        self.lblQuantity.setText(_translate("fruitPurchase", "Enter quantity:"))
        self.btnCalculate.setText(_translate("fruitPurchase", "Calculate Cost"))
        self.lblCost.setText(_translate("fruitPurchase", "Total Cost:"))
    
    def display_price(self):
        # Store the current selected fruit in the variable: fruit_selection
        fruit_selection = self.cmbFruit.currentText()
        if(fruit_selection in self.fruit_price.keys()):
            # Get the price per pound from the fruit_price dictionary
            price = self.fruit_price.get(fruit_selection) 
            # Display the price to the user by using the label
            self.lblPrice.setText(f"${price:.2f} per pound")
        else:
            self.lblPrice.setText("")

    def calculate(self):
        # To do: add input validation
        number_of_pounds = float(self.txtQuantity.text())
        fruit_selection = self.cmbFruit.currentText()
        if(fruit_selection in self.fruit_price.keys()):
            price = self.fruit_price.get(fruit_selection)
            total_cost = number_of_pounds*price
            self.txtCost.setText(str(f"${total_cost:.2f}"))
        else: 
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("Fruit Purchase")
            msg.setText("Please select a fruit")
            msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    fruitPurchase = QtWidgets.QMainWindow()
    ui = Ui_fruitPurchase()
    ui.setupUi(fruitPurchase)
    fruitPurchase.show()
    sys.exit(app.exec())
