# Form implementation generated from reading ui file 'studentperformance.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import pymysql as mdb

class Ui_studentPerformance(object):
    def setupUi(self, studentPerformance):
        studentPerformance.setObjectName("studentPerformance")
        studentPerformance.resize(661, 424)
        font = QtGui.QFont()
        font.setFamily("PMingLiU-ExtB")
        font.setPointSize(9)
        studentPerformance.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=studentPerformance)
        self.centralwidget.setObjectName("centralwidget")
        self.lblStudentId = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentId.setGeometry(QtCore.QRect(50, 100, 91, 21))
        self.lblStudentId.setObjectName("lblStudentId")
        self.txtStudentId = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentId.setGeometry(QtCore.QRect(150, 100, 131, 20))
        self.txtStudentId.setObjectName("txtStudentId")
        self.lblStudentName = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentName.setGeometry(QtCore.QRect(50, 140, 91, 21))
        self.lblStudentName.setObjectName("lblStudentName")
        self.txtStudentName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentName.setGeometry(QtCore.QRect(150, 140, 131, 20))
        self.txtStudentName.setObjectName("txtStudentName")
        self.lblStudentAge = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentAge.setGeometry(QtCore.QRect(50, 180, 91, 21))
        self.lblStudentAge.setObjectName("lblStudentAge")
        self.txtStudentAge = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentAge.setGeometry(QtCore.QRect(150, 180, 131, 20))
        self.txtStudentAge.setObjectName("txtStudentAge")
        self.txtStudentScore = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtStudentScore.setGeometry(QtCore.QRect(150, 220, 131, 20))
        self.txtStudentScore.setObjectName("txtStudentScore")
        self.lblStudentScore = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblStudentScore.setGeometry(QtCore.QRect(50, 220, 91, 21))
        self.lblStudentScore.setObjectName("lblStudentScore")
        self.btnInsert = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInsert.setGeometry(QtCore.QRect(50, 270, 111, 31))
        self.btnInsert.setObjectName("btnInsert")
        self.btnDisplay = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDisplay.setGeometry(QtCore.QRect(180, 270, 111, 31))
        self.btnDisplay.setObjectName("btnDisplay")
        self.lstData = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstData.setGeometry(QtCore.QRect(350, 30, 256, 341))
        self.lstData.setObjectName("lstData")
        studentPerformance.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=studentPerformance)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 661, 15))
        self.menubar.setObjectName("menubar")
        studentPerformance.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=studentPerformance)
        self.statusbar.setObjectName("statusbar")
        studentPerformance.setStatusBar(self.statusbar)

        self.retranslateUi(studentPerformance)
        QtCore.QMetaObject.connectSlotsByName(studentPerformance)
        
        self.btnInsert.clicked.connect(self.insert_data)
        self.btnDisplay.clicked.connect(self.display_data)

    def insert_data(self):
        
        try:
            sid = int(self.txtStudentId.text())
            sname = self.txtStudentName.text()
            sage = int(self.txtStudentAge.text())
            sscore = int(self.txtStudentScore.text())
            
            # Establish a database connection and store the connection obj in variable 'conn'
            conn = self.connecttodb()
            
            # Create a cursor object
            cursorobj = conn.cursor()
            cursorobj.execute("insert into studentinfo values (%s, %s, %s, %s)", [sid, sname, sage, sscore])
            
            # Commits the insert transaction to the database table
            conn.commit()            
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            # If connection object exists
            if(conn):
                conn.close()
    
    def display_data(self):
        
        try:
            conn = self.connecttodb()
            cursorobj = conn.cursor()
            cursorobj.execute("select * from studentinfo")
            results = cursorobj.fetchall()
            
            self.lstData.clear()
            self.lstData.addItem("ID    NAME    AGE    SCORE    PERFORMANCE")
            
            for row in results:
                sid, sname, sage, sscore = row
                if (sscore > 90):
                    performance = "Very Good"
                else:
                    performance = "Good"
                    
                    self.lstData.addItem(f"{sid} {sname} {sage} {sscore} {performance}")
        except Exception as e:
            print(e)
            print(type(e))
        finally:
            if(conn):
                conn.close()
    
    def connecttodb(self):
        connectionobj = mdb.connect(
            host = "localhost", 
            user = "studentdbuser2", 
            password = "studentdbuser2", 
            database = "studentinfodb", 
            port = 3306)
        print("Connected to the DB")
        return connectionobj
        
    def retranslateUi(self, studentPerformance):
        _translate = QtCore.QCoreApplication.translate
        studentPerformance.setWindowTitle(_translate("studentPerformance", "Student Performance"))
        self.lblStudentId.setText(_translate("studentPerformance", "Enter Student ID:"))
        self.lblStudentName.setText(_translate("studentPerformance", "Enter Student Name:"))
        self.lblStudentAge.setText(_translate("studentPerformance", "Enter Student Age:"))
        self.lblStudentScore.setText(_translate("studentPerformance", "Enter Student Score:"))
        self.btnInsert.setText(_translate("studentPerformance", "Insert Data"))
        self.btnDisplay.setText(_translate("studentPerformance", "Display Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    studentPerformance = QtWidgets.QMainWindow()
    ui = Ui_studentPerformance()
    ui.setupUi(studentPerformance)
    studentPerformance.show()
    sys.exit(app.exec())
